- name: Fetch IMDSv2 Token
  shell: |
    curl -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"
  register: imds_token
  changed_when: false

- name: Get Public IP
  shell: |
    curl -s -H "X-aws-ec2-metadata-token: {{ imds_token.stdout }}" \
    http://169.254.169.254/latest/meta-data/public-ipv4
  register: public_ip
  changed_when: false

- name: Set Jenkins URL
  set_fact:
    jenkins_url: "http://{{ public_ip.stdout }}:8080"

- name: Debug Jenkins URL
  debug:
    msg: "Jenkins URL is {{ jenkins_url }}"

- name: Copy SSL certificate file
  ansible.builtin.copy:
    src: /files/certs/jenkins.jks
    dest: /var/lib/jenkins/ssl/

- name: Copy Jenkins.yaml configuration file
  ansible.builtin.copy:
    src: /files/conf/jenkins.yaml
    dest: /var/lib/jenkins/casc_configs/

- name: Copy Jenkins service file
  ansible.builtin.copy:
    src: /files/conf/jenkins.service
    dest: /usr/lib/systemd/system/jenkins.service

- name: Copy all SSL certificate files
  ansible.builtin.copy:
    src: /files/crt/
    dest: /opt/csvn/data/conf/
    mode: preserve   # optional: to preserve the file modes

- name: Copy CSVN main HTTPD configuration file
  ansible.builtin.copy:
    src: /files/conf/csvn_main_httpd.conf
    dest: /opt/csvn/data/conf/

- name: Copy and replace AD password configuration file
  ansible.builtin.copy:
    src: /files/conf/svn_viewvc_httpd.conf
    dest: /opt/csvn/data/conf/

- name: Retrieve the secret value from AWS Secrets Manager
  community.aws.aws_secret:
    name: "JENKINS_HTTPS_KEYSTORE_PASSWORD"  # Directly inserting the secret name
    region: "us-east-1"     # Directly inserting the AWS region
  register: secret_output

- name: Ensure secret was retrieved successfully
  debug:
    msg: "Secret value is: {{ secret_output.secret }}"

- name: Update Jenkins service file with the secret value
  ansible.builtin.replace:
    path: "/usr/lib/systemd/system/jenkins.service"
    regexp: 'Environment="JENKINS_HTTPS_KEYSTORE_PASSWORD=.*"'
    replace: 'Environment="JENKINS_HTTPS_KEYSTORE_PASSWORD={{ secret_output.secret_string }}"'
  notify: Restart Jenkins

- name: Retrieve the AuthLDAPBindPassword secret value from AWS Secrets Manager
  amazon.aws.aws_secret:
    name: "AuthLDAPBindPassword"  # Secret name for AuthLDAPBindPassword
    region: "us-east-1"           # Directly inserting the AWS region
  register: ldap_secret_output

- name: Ensure LDAP secret was retrieved successfully
  debug:
    msg: "LDAP secret value is: {{ ldap_secret_output.secret_string }}"

- name: Update SVN ViewVC HTTPD configuration file with the LDAP secret value
  ansible.builtin.replace:
    path: "/opt/csvn/data/conf/svn_viewvc_httpd.conf"  # Directly inserting the file path
    regexp: 'AuthLDAPBindPassword ".*"'
    replace: 'AuthLDAPBindPassword "{{ ldap_secret_output.secret_string }}"'